name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build project
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Strip binary (*nix)
      if: matrix.os != 'windows-latest'
      run: strip target/release/bm2
    - name: Archive binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v1
      with:
        name: Linux
        path: target/release/bm2
    - name: Archive binary (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: Windows
        path: target/release/bm2.exe
    - name: Archive binary (macOS)
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v1
      with:
        name: macOS
        path: target/release/bm2
